"""Initial migration

Revision ID: 94365a14035d
Revises: 
Create Date: 2025-03-08 16:43:32.626540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94365a14035d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_age_group',
    sa.Column('age_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age_range', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('age_id'),
    sa.UniqueConstraint('age_range')
    )
    op.create_table('dim_date',
    sa.Column('date_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('date_id')
    )
    op.create_table('dim_device_type',
    sa.Column('device_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('device_type_id'),
    sa.UniqueConstraint('device_type_name')
    )
    op.create_table('dim_gender',
    sa.Column('gender_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('gender_id'),
    sa.UniqueConstraint('gender_name')
    )
    op.create_table('dim_placement',
    sa.Column('placement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placement_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('placement_id'),
    sa.UniqueConstraint('placement_name')
    )
    op.create_table('dim_platform',
    sa.Column('platform_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('platform_id'),
    sa.UniqueConstraint('platform_name')
    )
    op.create_table('dim_region',
    sa.Column('region_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('region_name')
    )
    op.create_table('fact_ad_metrics_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['age_id'], ['dim_age_group.age_id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['device_type_id'], ['dim_device_type.device_type_id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['dim_gender.gender_id'], ),
    sa.ForeignKeyConstraint(['placement_id'], ['dim_placement.placement_id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['dim_platform.platform_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_ad_metrics_daily')
    op.drop_table('dim_region')
    op.drop_table('dim_platform')
    op.drop_table('dim_placement')
    op.drop_table('dim_gender')
    op.drop_table('dim_device_type')
    op.drop_table('dim_date')
    op.drop_table('dim_age_group')
    # ### end Alembic commands ###
