metadata = {
    "dates": ['2021-03-30', '2024-01-04', '2025-01-21', '2021-04-30', '2022-10-18', '2024-12-12', '2025-02-04'],
    "regions": ["North America", "Europe", "Asia", "South America", "Africa", "Australia", "India"],
    "age_groups": ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
    "genders": ["Male", "Female", "Other"],
    "platforms": ["Facebook", "Google", "Instagram", "Twitter", "LinkedIn", "Snapchat"],
    "placements": ["News Feed", "Sidebar", "Search Results", "Stories", "Video Ads"],
    "device_types": ["Mobile", "Desktop", "Tablet"]
}

ad_metrics_data=[
  {
        "date_id": 7,
        "region_id": 4,
        "age_id": 5,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 4,
        "device_type_id": 2,
        "impressions": 14021,
        "clicks": 4877,
        "cost": 599.41,
        "conversions": 265,
        "likes": 1697
    },
  {
        "date_id": 3,
        "region_id": 5,
        "age_id": 6,
        "gender_id": 3,
        "platform_id": 5,
        "placement_id": 5,
        "device_type_id": 2,
        "impressions": 42836,
        "clicks": 2759,
        "cost": 690.8,
        "conversions": 13,
        "likes": 1852
    },
    {
        "date_id": 6,
        "region_id": 5,
        "age_id": 4,
        "gender_id": 2,
        "platform_id": 6,
        "placement_id": 3,
        "device_type_id": 2,
        "impressions": 15697,
        "clicks": 2787,
        "cost": 835.06,
        "conversions": 115,
        "likes": 878
    },
    {
        "date_id": 6,
        "region_id": 2,
        "age_id": 2,
        "gender_id": 3,
        "platform_id": 2,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 32134,
        "clicks": 2616,
        "cost": 616.08,
        "conversions": 328,
        "likes": 1732
    },
    {
        "date_id": 4,
        "region_id": 3,
        "age_id": 4,
        "gender_id": 3,
        "platform_id": 6,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 33213,
        "clicks": 1128,
        "cost": 412.58,
        "conversions": 439,
        "likes": 275
    },
    {
        "date_id": 2,
        "region_id": 4,
        "age_id": 4,
        "gender_id": 3,
        "platform_id": 2,
        "placement_id": 3,
        "device_type_id": 1,
        "impressions": 30246,
        "clicks": 3441,
        "cost": 736.65,
        "conversions": 161,
        "likes": 812
    },
    {
        "date_id": 1,
        "region_id": 7,
        "age_id": 4,
        "gender_id": 2,
        "platform_id": 2,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 41482,
        "clicks": 773,
        "cost": 292.77,
        "conversions": 120,
        "likes": 511
    },
    {
        "date_id": 7,
        "region_id": 5,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 4,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 19579,
        "clicks": 1505,
        "cost": 676.38,
        "conversions": 198,
        "likes": 587
    },
    {
        "date_id": 5,
        "region_id": 1,
        "age_id": 5,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 2,
        "device_type_id": 1,
        "impressions": 15105,
        "clicks": 3920,
        "cost": 725.78,
        "conversions": 70,
        "likes": 1261
    },
    {
        "date_id": 5,
        "region_id": 4,
        "age_id": 6,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 10055,
        "clicks": 1514,
        "cost": 698.71,
        "conversions": 152,
        "likes": 1017
    },
    {
        "date_id": 3,
        "region_id": 6,
        "age_id": 5,
        "gender_id": 2,
        "platform_id": 4,
        "placement_id": 3,
        "device_type_id": 1,
        "impressions": 49839,
        "clicks": 3722,
        "cost": 120.73,
        "conversions": 396,
        "likes": 837
    },
    {
        "date_id": 5,
        "region_id": 4,
        "age_id": 5,
        "gender_id": 2,
        "platform_id": 6,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 35265,
        "clicks": 3266,
        "cost": 698.93,
        "conversions": 284,
        "likes": 207
    },
    {
        "date_id": 3,
        "region_id": 5,
        "age_id": 2,
        "gender_id": 1,
        "platform_id": 3,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 14803,
        "clicks": 2028,
        "cost": 551.01,
        "conversions": 241,
        "likes": 1725
    },
    {
        "date_id": 3,
        "region_id": 1,
        "age_id": 1,
        "gender_id": 3,
        "platform_id": 4,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 44606,
        "clicks": 3484,
        "cost": 782.06,
        "conversions": 233,
        "likes": 1660
    },
    {
        "date_id": 1,
        "region_id": 1,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 6,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 32452,
        "clicks": 792,
        "cost": 495.09,
        "conversions": 464,
        "likes": 854
    },
    {
        "date_id": 1,
        "region_id": 7,
        "age_id": 1,
        "gender_id": 3,
        "platform_id": 5,
        "placement_id": 5,
        "device_type_id": 3,
        "impressions": 16624,
        "clicks": 4103,
        "cost": 850.18,
        "conversions": 434,
        "likes": 1150
    },
    {
        "date_id": 4,
        "region_id": 2,
        "age_id": 3,
        "gender_id": 3,
        "platform_id": 3,
        "placement_id": 1,
        "device_type_id": 3,
        "impressions": 34542,
        "clicks": 786,
        "cost": 339.5,
        "conversions": 198,
        "likes": 757
    },
    {
        "date_id": 4,
        "region_id": 1,
        "age_id": 1,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 4,
        "device_type_id": 2,
        "impressions": 29473,
        "clicks": 1760,
        "cost": 412.11,
        "conversions": 420,
        "likes": 1823
    },
    {
        "date_id": 7,
        "region_id": 7,
        "age_id": 5,
        "gender_id": 2,
        "platform_id": 2,
        "placement_id": 2,
        "device_type_id": 1,
        "impressions": 44191,
        "clicks": 3753,
        "cost": 284.44,
        "conversions": 336,
        "likes": 1311
    },
    {
        "date_id": 7,
        "region_id": 2,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 22968,
        "clicks": 2198,
        "cost": 541.84,
        "conversions": 256,
        "likes": 1219
    },
    {
        "date_id": 3,
        "region_id": 7,
        "age_id": 6,
        "gender_id": 3,
        "platform_id": 2,
        "placement_id": 1,
        "device_type_id": 1,
        "impressions": 39069,
        "clicks": 2506,
        "cost": 477.57,
        "conversions": 264,
        "likes": 1428
    },
    {
        "date_id": 3,
        "region_id": 5,
        "age_id": 3,
        "gender_id": 3,
        "platform_id": 6,
        "placement_id": 1,
        "device_type_id": 1,
        "impressions": 17330,
        "clicks": 2588,
        "cost": 230.59,
        "conversions": 225,
        "likes": 1869
    },
    {
        "date_id": 6,
        "region_id": 6,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 27010,
        "clicks": 4277,
        "cost": 867.6,
        "conversions": 202,
        "likes": 1497
    },
    {
        "date_id": 5,
        "region_id": 1,
        "age_id": 6,
        "gender_id": 2,
        "platform_id": 2,
        "placement_id": 5,
        "device_type_id": 2,
        "impressions": 19769,
        "clicks": 3601,
        "cost": 889.82,
        "conversions": 43,
        "likes": 1441
    },
    {
        "date_id": 6,
        "region_id": 3,
        "age_id": 2,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 1,
        "device_type_id": 3,
        "impressions": 37030,
        "clicks": 1020,
        "cost": 483.17,
        "conversions": 285,
        "likes": 1179
    },
    {
        "date_id": 7,
        "region_id": 2,
        "age_id": 1,
        "gender_id": 3,
        "platform_id": 2,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 26893,
        "clicks": 2063,
        "cost": 884.95,
        "conversions": 169,
        "likes": 951
    },
    {
        "date_id": 3,
        "region_id": 7,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 4,
        "placement_id": 3,
        "device_type_id": 2,
        "impressions": 30359,
        "clicks": 4251,
        "cost": 647.04,
        "conversions": 68,
        "likes": 603
    },
    {
        "date_id": 3,
        "region_id": 5,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 4,
        "placement_id": 2,
        "device_type_id": 3,
        "impressions": 47606,
        "clicks": 1637,
        "cost": 974.86,
        "conversions": 498,
        "likes": 1472
    },
    {
        "date_id": 7,
        "region_id": 7,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 5,
        "placement_id": 5,
        "device_type_id": 3,
        "impressions": 12973,
        "clicks": 3416,
        "cost": 951.79,
        "conversions": 390,
        "likes": 960
    },
    {
        "date_id": 7,
        "region_id": 6,
        "age_id": 1,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 4,
        "device_type_id": 1,
        "impressions": 39107,
        "clicks": 2966,
        "cost": 193.24,
        "conversions": 54,
        "likes": 825
    },
    {
        "date_id": 1,
        "region_id": 6,
        "age_id": 1,
        "gender_id": 2,
        "platform_id": 1,
        "placement_id": 3,
        "device_type_id": 1,
        "impressions": 33448,
        "clicks": 3991,
        "cost": 754.22,
        "conversions": 472,
        "likes": 1103
    },
    {
        "date_id": 1,
        "region_id": 3,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 2,
        "placement_id": 2,
        "device_type_id": 1,
        "impressions": 43475,
        "clicks": 4532,
        "cost": 147.45,
        "conversions": 482,
        "likes": 1232
    },
    {
        "date_id": 1,
        "region_id": 3,
        "age_id": 4,
        "gender_id": 3,
        "platform_id": 6,
        "placement_id": 2,
        "device_type_id": 3,
        "impressions": 46561,
        "clicks": 2718,
        "cost": 857.02,
        "conversions": 316,
        "likes": 242
    },
    {
        "date_id": 6,
        "region_id": 7,
        "age_id": 1,
        "gender_id": 1,
        "platform_id": 2,
        "placement_id": 5,
        "device_type_id": 1,
        "impressions": 20893,
        "clicks": 1823,
        "cost": 859.81,
        "conversions": 365,
        "likes": 1835
    },
    {
        "date_id": 6,
        "region_id": 6,
        "age_id": 2,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 1,
        "device_type_id": 3,
        "impressions": 17914,
        "clicks": 1532,
        "cost": 157.07,
        "conversions": 160,
        "likes": 1717
    },
    {
        "date_id": 3,
        "region_id": 4,
        "age_id": 1,
        "gender_id": 1,
        "platform_id": 5,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 12219,
        "clicks": 2571,
        "cost": 263.91,
        "conversions": 33,
        "likes": 1959
    },
    {
        "date_id": 5,
        "region_id": 4,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 34630,
        "clicks": 1381,
        "cost": 446.7,
        "conversions": 360,
        "likes": 401
    },
    {
        "date_id": 7,
        "region_id": 5,
        "age_id": 6,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 15415,
        "clicks": 3053,
        "cost": 608.52,
        "conversions": 442,
        "likes": 1156
    },
    {
        "date_id": 3,
        "region_id": 7,
        "age_id": 2,
        "gender_id": 3,
        "platform_id": 3,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 29020,
        "clicks": 1051,
        "cost": 574.08,
        "conversions": 405,
        "likes": 1934
    },
    {
        "date_id": 1,
        "region_id": 5,
        "age_id": 3,
        "gender_id": 1,
        "platform_id": 5,
        "placement_id": 2,
        "device_type_id": 1,
        "impressions": 38034,
        "clicks": 1798,
        "cost": 269.43,
        "conversions": 244,
        "likes": 936
    },
    {
        "date_id": 4,
        "region_id": 6,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 1,
        "placement_id": 5,
        "device_type_id": 3,
        "impressions": 35231,
        "clicks": 4935,
        "cost": 401.08,
        "conversions": 76,
        "likes": 1199
    },
    {
        "date_id": 1,
        "region_id": 3,
        "age_id": 6,
        "gender_id": 2,
        "platform_id": 5,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 15485,
        "clicks": 1810,
        "cost": 833.78,
        "conversions": 319,
        "likes": 1014
    },
    {
        "date_id": 6,
        "region_id": 5,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 3,
        "placement_id": 4,
        "device_type_id": 2,
        "impressions": 37417,
        "clicks": 2987,
        "cost": 399.91,
        "conversions": 86,
        "likes": 844
    },
    {
        "date_id": 7,
        "region_id": 5,
        "age_id": 4,
        "gender_id": 1,
        "platform_id": 1,
        "placement_id": 2,
        "device_type_id": 3,
        "impressions": 41550,
        "clicks": 1256,
        "cost": 871.45,
        "conversions": 103,
        "likes": 948
    },
    {
        "date_id": 2,
        "region_id": 3,
        "age_id": 4,
        "gender_id": 1,
        "platform_id": 5,
        "placement_id": 2,
        "device_type_id": 1,
        "impressions": 25835,
        "clicks": 4621,
        "cost": 651.85,
        "conversions": 476,
        "likes": 956
    },
    {
        "date_id": 5,
        "region_id": 3,
        "age_id": 6,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 5,
        "device_type_id": 3,
        "impressions": 34507,
        "clicks": 2292,
        "cost": 332.69,
        "conversions": 19,
        "likes": 757
    },
    {
        "date_id": 4,
        "region_id": 2,
        "age_id": 1,
        "gender_id": 3,
        "platform_id": 4,
        "placement_id": 4,
        "device_type_id": 2,
        "impressions": 49453,
        "clicks": 1375,
        "cost": 401.17,
        "conversions": 246,
        "likes": 834
    },
    {
        "date_id": 7,
        "region_id": 4,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 5,
        "device_type_id": 1,
        "impressions": 18790,
        "clicks": 1979,
        "cost": 737.71,
        "conversions": 88,
        "likes": 1044
    },
    {
        "date_id": 7,
        "region_id": 2,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 1,
        "placement_id": 5,
        "device_type_id": 1,
        "impressions": 34393,
        "clicks": 3228,
        "cost": 121.14,
        "conversions": 460,
        "likes": 425
    },
    {
        "date_id": 2,
        "region_id": 4,
        "age_id": 6,
        "gender_id": 2,
        "platform_id": 4,
        "placement_id": 5,
        "device_type_id": 1,
        "impressions": 31969,
        "clicks": 547,
        "cost": 343.91,
        "conversions": 248,
        "likes": 1591
    },
    {
        "date_id": 4,
        "region_id": 7,
        "age_id": 2,
        "gender_id": 3,
        "platform_id": 4,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 20895,
        "clicks": 4054,
        "cost": 508.17,
        "conversions": 316,
        "likes": 1778
    },
    {
        "date_id": 5,
        "region_id": 5,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 3,
        "device_type_id": 2,
        "impressions": 13160,
        "clicks": 2838,
        "cost": 941.13,
        "conversions": 246,
        "likes": 1170
    },
    {
        "date_id": 3,
        "region_id": 4,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 1,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 36194,
        "clicks": 1022,
        "cost": 784.48,
        "conversions": 151,
        "likes": 1630
    },
    {
        "date_id": 5,
        "region_id": 6,
        "age_id": 5,
        "gender_id": 3,
        "platform_id": 6,
        "placement_id": 4,
        "device_type_id": 2,
        "impressions": 48164,
        "clicks": 1265,
        "cost": 336.61,
        "conversions": 100,
        "likes": 169
    },
    {
        "date_id": 2,
        "region_id": 1,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 3,
        "device_type_id": 2,
        "impressions": 20659,
        "clicks": 1199,
        "cost": 113.75,
        "conversions": 299,
        "likes": 1688
    },
    {
        "date_id": 7,
        "region_id": 7,
        "age_id": 5,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 5,
        "device_type_id": 2,
        "impressions": 45443,
        "clicks": 1714,
        "cost": 720.82,
        "conversions": 94,
        "likes": 924
    },
    {
        "date_id": 2,
        "region_id": 6,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 4,
        "placement_id": 2,
        "device_type_id": 3,
        "impressions": 23253,
        "clicks": 3623,
        "cost": 547.04,
        "conversions": 313,
        "likes": 1529
    },
    {
        "date_id": 1,
        "region_id": 2,
        "age_id": 2,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 3,
        "device_type_id": 1,
        "impressions": 49464,
        "clicks": 4089,
        "cost": 936.33,
        "conversions": 375,
        "likes": 1021
    },
    {
        "date_id": 5,
        "region_id": 2,
        "age_id": 5,
        "gender_id": 3,
        "platform_id": 6,
        "placement_id": 3,
        "device_type_id": 1,
        "impressions": 24570,
        "clicks": 3047,
        "cost": 623.72,
        "conversions": 395,
        "likes": 1688
    },
    {
        "date_id": 6,
        "region_id": 1,
        "age_id": 1,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 13505,
        "clicks": 3011,
        "cost": 231.07,
        "conversions": 104,
        "likes": 828
    },
    {
        "date_id": 6,
        "region_id": 6,
        "age_id": 3,
        "gender_id": 3,
        "platform_id": 4,
        "placement_id": 4,
        "device_type_id": 2,
        "impressions": 35003,
        "clicks": 1590,
        "cost": 142.42,
        "conversions": 380,
        "likes": 1692
    },
    {
        "date_id": 5,
        "region_id": 3,
        "age_id": 6,
        "gender_id": 1,
        "platform_id": 1,
        "placement_id": 3,
        "device_type_id": 2,
        "impressions": 19950,
        "clicks": 1981,
        "cost": 689.47,
        "conversions": 226,
        "likes": 851
    },
    {
        "date_id": 6,
        "region_id": 7,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 1,
        "device_type_id": 1,
        "impressions": 43432,
        "clicks": 4701,
        "cost": 911.57,
        "conversions": 163,
        "likes": 1580
    },
    {
        "date_id": 4,
        "region_id": 5,
        "age_id": 5,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 2,
        "device_type_id": 1,
        "impressions": 35100,
        "clicks": 3102,
        "cost": 778.71,
        "conversions": 381,
        "likes": 833
    },
    {
        "date_id": 4,
        "region_id": 2,
        "age_id": 3,
        "gender_id": 1,
        "platform_id": 5,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 41740,
        "clicks": 4625,
        "cost": 800.51,
        "conversions": 194,
        "likes": 1353
    },
    {
        "date_id": 4,
        "region_id": 3,
        "age_id": 1,
        "gender_id": 3,
        "platform_id": 5,
        "placement_id": 4,
        "device_type_id": 1,
        "impressions": 11005,
        "clicks": 2500,
        "cost": 593.2,
        "conversions": 409,
        "likes": 1183
    },
    {
        "date_id": 3,
        "region_id": 3,
        "age_id": 6,
        "gender_id": 1,
        "platform_id": 2,
        "placement_id": 2,
        "device_type_id": 3,
        "impressions": 42710,
        "clicks": 1729,
        "cost": 405.87,
        "conversions": 402,
        "likes": 1149
    },
    {
        "date_id": 3,
        "region_id": 7,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 2,
        "placement_id": 2,
        "device_type_id": 3,
        "impressions": 17313,
        "clicks": 3422,
        "cost": 561.45,
        "conversions": 38,
        "likes": 1422
    },
    {
        "date_id": 7,
        "region_id": 6,
        "age_id": 3,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 4,
        "device_type_id": 1,
        "impressions": 16666,
        "clicks": 1537,
        "cost": 779.78,
        "conversions": 200,
        "likes": 995
    },
    {
        "date_id": 6,
        "region_id": 1,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 5,
        "placement_id": 5,
        "device_type_id": 3,
        "impressions": 20304,
        "clicks": 2532,
        "cost": 487.35,
        "conversions": 210,
        "likes": 1200
    },
    {
        "date_id": 4,
        "region_id": 4,
        "age_id": 5,
        "gender_id": 3,
        "platform_id": 3,
        "placement_id": 1,
        "device_type_id": 1,
        "impressions": 44425,
        "clicks": 2153,
        "cost": 237.24,
        "conversions": 201,
        "likes": 1409
    },
    {
        "date_id": 6,
        "region_id": 5,
        "age_id": 6,
        "gender_id": 1,
        "platform_id": 4,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 30736,
        "clicks": 3376,
        "cost": 625.13,
        "conversions": 31,
        "likes": 1067
    },
    {
        "date_id": 2,
        "region_id": 2,
        "age_id": 2,
        "gender_id": 3,
        "platform_id": 5,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 34589,
        "clicks": 2402,
        "cost": 576.98,
        "conversions": 298,
        "likes": 1473
    },
    {
        "date_id": 1,
        "region_id": 7,
        "age_id": 2,
        "gender_id": 3,
        "platform_id": 2,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 10317,
        "clicks": 620,
        "cost": 379.42,
        "conversions": 176,
        "likes": 1252
    },
    {
        "date_id": 5,
        "region_id": 3,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 3,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 46406,
        "clicks": 2083,
        "cost": 354.08,
        "conversions": 143,
        "likes": 122
    },
    {
        "date_id": 1,
        "region_id": 6,
        "age_id": 3,
        "gender_id": 3,
        "platform_id": 4,
        "placement_id": 3,
        "device_type_id": 1,
        "impressions": 26831,
        "clicks": 1495,
        "cost": 958.85,
        "conversions": 29,
        "likes": 688
    },
    {
        "date_id": 2,
        "region_id": 5,
        "age_id": 2,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 49936,
        "clicks": 1212,
        "cost": 561.69,
        "conversions": 305,
        "likes": 527
    },
    {
        "date_id": 6,
        "region_id": 3,
        "age_id": 6,
        "gender_id": 2,
        "platform_id": 4,
        "placement_id": 2,
        "device_type_id": 1,
        "impressions": 47404,
        "clicks": 4731,
        "cost": 855.05,
        "conversions": 245,
        "likes": 743
    },
    {
        "date_id": 2,
        "region_id": 4,
        "age_id": 1,
        "gender_id": 2,
        "platform_id": 2,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 16263,
        "clicks": 846,
        "cost": 931.75,
        "conversions": 39,
        "likes": 237
    },
    {
        "date_id": 1,
        "region_id": 4,
        "age_id": 6,
        "gender_id": 3,
        "platform_id": 4,
        "placement_id": 1,
        "device_type_id": 2,
        "impressions": 32855,
        "clicks": 1949,
        "cost": 590.74,
        "conversions": 132,
        "likes": 1186
    },
    {
        "date_id": 3,
        "region_id": 4,
        "age_id": 3,
        "gender_id": 1,
        "platform_id": 4,
        "placement_id": 2,
        "device_type_id": 1,
        "impressions": 16008,
        "clicks": 2587,
        "cost": 731.27,
        "conversions": 202,
        "likes": 1893
    },
    {
        "date_id": 1,
        "region_id": 1,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 4,
        "placement_id": 4,
        "device_type_id": 1,
        "impressions": 23634,
        "clicks": 2184,
        "cost": 996.41,
        "conversions": 453,
        "likes": 1563
    },
    {
        "date_id": 4,
        "region_id": 2,
        "age_id": 3,
        "gender_id": 3,
        "platform_id": 5,
        "placement_id": 5,
        "device_type_id": 2,
        "impressions": 30465,
        "clicks": 4425,
        "cost": 179.82,
        "conversions": 126,
        "likes": 1028
    },
    {
        "date_id": 5,
        "region_id": 3,
        "age_id": 1,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 5,
        "device_type_id": 2,
        "impressions": 26935,
        "clicks": 2476,
        "cost": 370.1,
        "conversions": 486,
        "likes": 530
    },
    {
        "date_id": 7,
        "region_id": 3,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 5,
        "placement_id": 2,
        "device_type_id": 2,
        "impressions": 15117,
        "clicks": 4098,
        "cost": 322.57,
        "conversions": 48,
        "likes": 1756
    },
    {
        "date_id": 5,
        "region_id": 2,
        "age_id": 4,
        "gender_id": 1,
        "platform_id": 4,
        "placement_id": 4,
        "device_type_id": 1,
        "impressions": 44707,
        "clicks": 1695,
        "cost": 764.24,
        "conversions": 135,
        "likes": 1782
    },
    {
        "date_id": 4,
        "region_id": 3,
        "age_id": 1,
        "gender_id": 1,
        "platform_id": 4,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 32219,
        "clicks": 3542,
        "cost": 527.68,
        "conversions": 310,
        "likes": 284
    },
    {
        "date_id": 4,
        "region_id": 2,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 3,
        "placement_id": 2,
        "device_type_id": 2,
        "impressions": 42582,
        "clicks": 1588,
        "cost": 364.55,
        "conversions": 254,
        "likes": 55
    },
    {
        "date_id": 2,
        "region_id": 3,
        "age_id": 4,
        "gender_id": 1,
        "platform_id": 3,
        "placement_id": 1,
        "device_type_id": 3,
        "impressions": 12544,
        "clicks": 2485,
        "cost": 153.44,
        "conversions": 297,
        "likes": 100
    },
    {
        "date_id": 6,
        "region_id": 6,
        "age_id": 1,
        "gender_id": 2,
        "platform_id": 5,
        "placement_id": 5,
        "device_type_id": 3,
        "impressions": 42431,
        "clicks": 978,
        "cost": 237.96,
        "conversions": 171,
        "likes": 1046
    },
    {
        "date_id": 1,
        "region_id": 2,
        "age_id": 5,
        "gender_id": 3,
        "platform_id": 3,
        "placement_id": 3,
        "device_type_id": 3,
        "impressions": 48997,
        "clicks": 882,
        "cost": 914.91,
        "conversions": 122,
        "likes": 1799
    },
    {
        "date_id": 1,
        "region_id": 6,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 6,
        "placement_id": 5,
        "device_type_id": 2,
        "impressions": 32549,
        "clicks": 4109,
        "cost": 655.67,
        "conversions": 254,
        "likes": 145
    },
    {
        "date_id": 4,
        "region_id": 2,
        "age_id": 1,
        "gender_id": 1,
        "platform_id": 1,
        "placement_id": 4,
        "device_type_id": 1,
        "impressions": 38260,
        "clicks": 2140,
        "cost": 953.82,
        "conversions": 433,
        "likes": 281
    },
    {
        "date_id": 7,
        "region_id": 4,
        "age_id": 2,
        "gender_id": 2,
        "platform_id": 4,
        "placement_id": 1,
        "device_type_id": 3,
        "impressions": 14613,
        "clicks": 1984,
        "cost": 167.86,
        "conversions": 426,
        "likes": 399
    },
    {
        "date_id": 1,
        "region_id": 4,
        "age_id": 3,
        "gender_id": 3,
        "platform_id": 5,
        "placement_id": 3,
        "device_type_id": 1,
        "impressions": 10147,
        "clicks": 2247,
        "cost": 139.1,
        "conversions": 320,
        "likes": 263
    },
    {
        "date_id": 5,
        "region_id": 2,
        "age_id": 4,
        "gender_id": 2,
        "platform_id": 2,
        "placement_id": 1,
        "device_type_id": 3,
        "impressions": 19229,
        "clicks": 3308,
        "cost": 142.1,
        "conversions": 456,
        "likes": 275
    },
    {
        "date_id": 7,
        "region_id": 2,
        "age_id": 1,
        "gender_id": 3,
        "platform_id": 2,
        "placement_id": 2,
        "device_type_id": 3,
        "impressions": 18063,
        "clicks": 1679,
        "cost": 967.39,
        "conversions": 253,
        "likes": 1847
    },
    {
        "date_id": 4,
        "region_id": 6,
        "age_id": 5,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 5,
        "device_type_id": 1,
        "impressions": 32967,
        "clicks": 3761,
        "cost": 890.1,
        "conversions": 87,
        "likes": 53
    },
    {
        "date_id": 3,
        "region_id": 7,
        "age_id": 2,
        "gender_id": 3,
        "platform_id": 1,
        "placement_id": 5,
        "device_type_id": 1,
        "impressions": 16069,
        "clicks": 1115,
        "cost": 295.68,
        "conversions": 34,
        "likes": 1461
    },
    {
        "date_id": 6,
        "region_id": 4,
        "age_id": 5,
        "gender_id": 2,
        "platform_id": 3,
        "placement_id": 2,
        "device_type_id": 2,
        "impressions": 26903,
        "clicks": 3669,
        "cost": 176.24,
        "conversions": 418,
        "likes": 1328
    },
    {
        "date_id": 3,
        "region_id": 3,
        "age_id": 4,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 39938,
        "clicks": 4460,
        "cost": 428.73,
        "conversions": 284,
        "likes": 1958
    },
    {
        "date_id": 5,
        "region_id": 5,
        "age_id": 6,
        "gender_id": 1,
        "platform_id": 6,
        "placement_id": 3,
        "device_type_id": 1,
        "impressions": 15688,
        "clicks": 3725,
        "cost": 959.63,
        "conversions": 122,
        "likes": 1163
    },
    {
        "date_id": 3,
        "region_id": 3,
        "age_id": 5,
        "gender_id": 3,
        "platform_id": 4,
        "placement_id": 5,
        "device_type_id": 3,
        "impressions": 14590,
        "clicks": 2448,
        "cost": 106.66,
        "conversions": 377,
        "likes": 881
    },
    {
        "date_id": 7,
        "region_id": 5,
        "age_id": 2,
        "gender_id": 1,
        "platform_id": 5,
        "placement_id": 3,
        "device_type_id": 2,
        "impressions": 23117,
        "clicks": 931,
        "cost": 849.16,
        "conversions": 110,
        "likes": 1883
    },
    {
        "date_id": 5,
        "region_id": 4,
        "age_id": 3,
        "gender_id": 2,
        "platform_id": 6,
        "placement_id": 2,
        "device_type_id": 2,
        "impressions": 30608,
        "clicks": 2244,
        "cost": 149.43,
        "conversions": 122,
        "likes": 219
    },
    {
        "date_id": 1,
        "region_id": 3,
        "age_id": 4,
        "gender_id": 3,
        "platform_id": 2,
        "placement_id": 4,
        "device_type_id": 2,
        "impressions": 31956,
        "clicks": 3389,
        "cost": 477.33,
        "conversions": 363,
        "likes": 1231
    },
    {
        "date_id": 6,
        "region_id": 2,
        "age_id": 6,
        "gender_id": 3,
        "platform_id": 6,
        "placement_id": 4,
        "device_type_id": 3,
        "impressions": 31094,
        "clicks": 4538,
        "cost": 731.15,
        "conversions": 298,
        "likes": 165
    },
    {
        "date_id": 4,
        "region_id": 2,
        "age_id": 4,
        "gender_id": 2,
        "platform_id": 2,
        "placement_id": 5,
        "device_type_id": 3,
        "impressions": 45577,
        "clicks": 1076,
        "cost": 218.67,
        "conversions": 344,
        "likes": 1848
    },
    {
        "date_id": 4,
        "region_id": 7,
        "age_id": 1,
        "gender_id": 2,
        "platform_id": 6,
        "placement_id": 4,
        "device_type_id": 1,
        "impressions": 15472,
        "clicks": 791,
        "cost": 393.26,
        "conversions": 135,
        "likes": 1692
    },
    
]
